# Generated by Django 5.2.5 on 2025-08-20 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemRequisicaoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição do Serviço/Medição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor (R$)')),
            ],
            options={
                'verbose_name': 'Item de Serviço',
                'verbose_name_plural': 'Itens de Serviço',
            },
        ),
        migrations.CreateModel(
            name='Requisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MATERIAL', 'Requisição de Material'), ('SERVICO', 'Requisição de Serviço')], max_length=8, verbose_name='Tipo de Requisição')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Solicitação')),
                ('justificativa', models.TextField()),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('APROVADA', 'Aprovada'), ('REPROVADA', 'Reprovada'), ('ATENDIDA', 'Atendida')], default='ABERTA', max_length=10)),
            ],
            options={
                'verbose_name': 'Requisição',
                'verbose_name_plural': 'Requisições',
                'ordering': ['-data_solicitacao'],
            },
        ),
        migrations.CreateModel(
            name='ItemRequisicaoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_solicitada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Item de Material',
                'verbose_name_plural': 'Itens de Material',
            },
        ),
    ]
