# Generated by Django 5.2.5 on 2025-08-20 03:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requisicoes', '0001_initial'),
        ('servidores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicao',
            name='setor_solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servidores.setor', verbose_name='Setor Solicitante'),
        ),
        migrations.AddField(
            model_name='requisicao',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisicoes_solicitadas', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante'),
        ),
        migrations.AddField(
            model_name='itemrequisicaoservico',
            name='requisicao',
            field=models.ForeignKey(limit_choices_to={'tipo': 'SERVICO'}, on_delete=django.db.models.deletion.CASCADE, related_name='itens_servico', to='requisicoes.requisicao'),
        ),
        migrations.AddField(
            model_name='itemrequisicaomaterial',
            name='requisicao',
            field=models.ForeignKey(limit_choices_to={'tipo': 'MATERIAL'}, on_delete=django.db.models.deletion.CASCADE, related_name='itens_material', to='requisicoes.requisicao'),
        ),
    ]
