# Generated by Django 5.2.5 on 2025-08-27 02:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicoes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicao',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='requisicao',
            name='numero_requisicao',
            field=models.CharField(blank=True, editable=False, max_length=25, null=True, unique=True),
        ),
    ]
