# Generated by Django 5.2.5 on 2025-08-27 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requisicoes', '0003_requisicao_created_at_requisicao_numero_requisicao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisicao',
            name='created_at',
        ),
    ]
