# Generated by Django 5.2.5 on 2025-08-20 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Modalidade de Licitação',
                'verbose_name_plural': 'Modalidades de Licitação',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Licitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_processo', models.CharField(max_length=50, unique=True, verbose_name='Número do Processo')),
                ('objeto', models.TextField()),
                ('data_abertura', models.DateField(verbose_name='Data de Abertura')),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='licitacoes.modalidade', verbose_name='Modalidade')),
            ],
            options={
                'verbose_name': 'Licitação',
                'verbose_name_plural': 'Licitações',
                'ordering': ['-data_abertura'],
            },
        ),
    ]
