# Generated by Django 5.2.5 on 2025-11-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='licitacao',
            name='data_fim',
            field=models.DateField(blank=True, help_text='Data prevista para o fim da licitação ou validade da ata.', null=True, verbose_name='Data de Encerramento'),
        ),
        migrations.AddField(
            model_name='licitacao',
            name='valor_global',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Valor Global Estimado'),
        ),
    ]
