# Generated by Django 5.2.5 on 2025-08-20 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrato', models.CharField(max_length=50, verbose_name='Número do Contrato')),
                ('ano_contrato', models.PositiveIntegerField(verbose_name='Ano do Contrato')),
                ('objeto', models.TextField()),
                ('valor_global', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_assinatura', models.DateField(verbose_name='Data de Assinatura')),
                ('data_vigencia_fim', models.DateField(verbose_name='Fim da Vigência')),
                ('status', models.CharField(choices=[('VIGENTE', 'Vigente'), ('ENCERRADO', 'Encerrado'), ('SUSPENSO', 'Suspenso'), ('RESCINDIDO', 'Rescindido')], default='VIGENTE', max_length=10)),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-ano_contrato', '-numero_contrato'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('arquivo', models.FileField(upload_to='contratos_documentos/')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
        migrations.CreateModel(
            name='ItemContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição do Item')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name': 'Item do Contrato',
                'verbose_name_plural': 'Itens do Contrato',
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField(verbose_name='Data do Pagamento')),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-data_pagamento'],
            },
        ),
        migrations.CreateModel(
            name='Recebimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_recebida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_recebimento', models.DateField(verbose_name='Data do Recebimento')),
            ],
            options={
                'verbose_name': 'Recebimento de Item',
                'verbose_name_plural': 'Recebimentos de Itens',
                'ordering': ['-data_recebimento'],
            },
        ),
    ]
