# Generated by Django 5.2.5 on 2025-11-23 23:22

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estoque', '0001_initial'),
        ('fornecedores', '0001_initial'),
        ('licitacoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrato', models.CharField(max_length=50, verbose_name='Número do Contrato')),
                ('ano_contrato', models.PositiveIntegerField(verbose_name='Ano do Contrato')),
                ('objeto', models.TextField()),
                ('valor_global', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_assinatura', models.DateField(verbose_name='Data de Assinatura')),
                ('data_vigencia_fim', models.DateField(verbose_name='Fim da Vigência')),
                ('status', models.CharField(choices=[('VIGENTE', 'Vigente'), ('ENCERRADO', 'Encerrado'), ('SUSPENSO', 'Suspenso'), ('RESCINDIDO', 'Rescindido')], default='VIGENTE', max_length=10)),
                ('fiscal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_fiscalizados', to=settings.AUTH_USER_MODEL)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_fornecedores', to='fornecedores.fornecedor')),
                ('licitacao_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='licitacoes.licitacao', verbose_name='Licitação de Origem')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-ano_contrato', '-numero_contrato'],
                'unique_together': {('numero_contrato', 'ano_contrato')},
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('arquivo', models.FileField(upload_to='contratos_documentos/')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='contratos.contrato')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
        migrations.CreateModel(
            name='ItemContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição do Item')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='contratos.contrato')),
                ('produto_catalogo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.produto', verbose_name='Produto do Catálogo')),
            ],
            options={
                'verbose_name': 'Item do Contrato',
                'verbose_name_plural': 'Itens do Contrato',
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField(verbose_name='Data do Pagamento')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='contratos.contrato')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-data_pagamento'],
            },
        ),
        migrations.CreateModel(
            name='PedidoEntregaFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_solicitacao', models.DateField(default=datetime.date.today, verbose_name='Data da Solicitação')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PARCIAL', 'Parcialmente Atendido'), ('ATENDIDO', 'Atendido'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=10, verbose_name='Status do Pedido')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_entrega', to='contratos.contrato', verbose_name='Contrato Associado')),
            ],
            options={
                'verbose_name': 'Pedido de Entrega ao Fornecedor',
                'verbose_name_plural': 'Pedidos de Entrega ao Fornecedor',
                'ordering': ['-data_solicitacao'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedidoEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_solicitada', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade Solicitada')),
                ('item_contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_associados', to='contratos.itemcontrato')),
                ('pedido_entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_solicitados', to='contratos.pedidoentregafornecedor')),
            ],
            options={
                'verbose_name': 'Item de Pedido de Entrega',
                'verbose_name_plural': 'Itens de Pedido de Entrega',
                'ordering': ['item_contrato__descricao'],
                'unique_together': {('pedido_entrega', 'item_contrato')},
            },
        ),
        migrations.CreateModel(
            name='Recebimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_recebida', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade Recebida')),
                ('data_recebimento', models.DateField(default=datetime.date.today, verbose_name='Data do Recebimento')),
                ('item_pedido_entrega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recebimentos', to='contratos.itempedidoentrega', verbose_name='Item do Pedido de Entrega')),
            ],
            options={
                'verbose_name': 'Recebimento de Item',
                'verbose_name_plural': 'Recebimentos de Itens',
                'ordering': ['-data_recebimento'],
            },
        ),
    ]
