# Generated by Django 5.2.5 on 2025-08-20 03:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contratos', '0001_initial'),
        ('estoque', '0001_initial'),
        ('fornecedores', '0001_initial'),
        ('licitacoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='fiscal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_fiscalizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contrato',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='fornecedores.fornecedor'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='licitacao_origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='licitacoes.licitacao', verbose_name='Licitação de Origem'),
        ),
        migrations.AddField(
            model_name='documento',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='contratos.contrato'),
        ),
        migrations.AddField(
            model_name='itemcontrato',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='contratos.contrato'),
        ),
        migrations.AddField(
            model_name='itemcontrato',
            name='produto_catalogo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.produto', verbose_name='Produto do Catálogo'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='contratos.contrato'),
        ),
        migrations.AddField(
            model_name='recebimento',
            name='item_contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recebimentos', to='contratos.itemcontrato'),
        ),
        migrations.AlterUniqueTogether(
            name='contrato',
            unique_together={('numero_contrato', 'ano_contrato')},
        ),
    ]
