# Generated by Django 5.2.5 on 2025-11-25 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recebimento',
            name='item_pedido_entrega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recebimentos', to='contratos.itempedidoentrega', verbose_name='Item do Pedido'),
        ),
    ]
