# Generated by Django 5.2.5 on 2025-08-28 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagamento',
            old_name='valor_pago',
            new_name='valor',
        ),
        migrations.AddField(
            model_name='pagamento',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
    ]
